import Head from 'next/head';
import HomeHead from '../components/DashboardPage/HomeHead';
import Banner from '@/components/DashboardPage/Banner';
import HomeDetails from '@/components/DashboardPage/HomeDetails';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHead />
      <Banner />
      <HomeDetails />
    </>
  );
}
